# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bindplane < Formula
  desc ""
  homepage "https://github.com/observIQ/bindplane-op"
  version "1.15.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.15.0/bindplane-v1.15.0-darwin-amd64.zip"
      sha256 "dac9bc5ad9986d76b98d0ec76208612a0edbbdaaa30654eb983dc1d24eb71510"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.15.0/bindplane-v1.15.0-darwin-arm64.zip"
      sha256 "453610ed8b263ee12a325507fd4a9f9574a4df58a5a536f815a001e228da992a"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.15.0/bindplane-v1.15.0-linux-amd64.zip"
      sha256 "566dd2f54c0a1ce48419449c60b587832ae749e93534d14dd38aeba3a9530f0e"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.15.0/bindplane-v1.15.0-linux-arm64.zip"
      sha256 "a48fc55299ad3c5b9ebd058adeefc561181917630d296cf98a47de0b455f06c4"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.15.0/bindplane-v1.15.0-linux-arm.zip"
      sha256 "289f4dde491a432a5240fb99e19b55a03e8b3c67fc459ce07820de6a65813a92"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
  end
end
