# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bindplane < Formula
  desc ""
  homepage "https://github.com/observIQ/bindplane-op"
  version "1.19.0"
  license "Apache 2.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.19.0/bindplane-v1.19.0-linux-amd64.zip"
      sha256 "1c85d7426a7984c20076b87e4c832507afc4423df336b2be2ed4d66ff5a7505f"

      def install
        bin.install "bindplane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.19.0/bindplane-v1.19.0-linux-arm64.zip"
      sha256 "834fdb13c4b75031e36e2fc24a188f9b4a300dc28f5cece10edcec32a9a96450"

      def install
        bin.install "bindplane"
      end
    end
  end
end
