# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bindplane < Formula
  desc ""
  homepage "https://github.com/observIQ/bindplane-op"
  version "1.9.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.9.2/bindplane-v1.9.2-darwin-amd64.zip"
      sha256 "b223200229e039df404af55810facd25f08f8a9f7e31b67d2f70447c4e58c898"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.9.2/bindplane-v1.9.2-darwin-arm64.zip"
      sha256 "b7647b9c125d7210e55ea1f1a7d85b041c0848e040e00263ec5a21171d569431"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.9.2/bindplane-v1.9.2-linux-amd64.zip"
      sha256 "5be14aaa65e55b223a78a5f701116a5c1a2740db06f1504d95439a3b05f07db8"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.9.2/bindplane-v1.9.2-linux-arm64.zip"
      sha256 "334dec1ded4f9d992b7886d17e656781d197b0d2c6e2dfeefcc87adf81ddbb5c"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/bindplane-op/releases/download/v1.9.2/bindplane-v1.9.2-linux-arm.zip"
      sha256 "14de570bb0c6ed263b4b30024cd83736c5fcb3abf137ac34c8bb6db471d2685a"

      def install
        bin.install "bindplane"
        bin.install "bindplanectl"
      end
    end
  end
end
